language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - mysql -e 'CREATE DATABASE sca;'
script:
  - python manage.py test --settings=sca.settings.test
  - coverage run --source=sca.apps.schedule manage.py test --settings=sca.settings.test
after_success:
  - coveralls
