# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20160402_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='code',
            field=models.CharField(default='hogehogehoge', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
