# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20160410_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.IntegerField(choices=[(0, 'NG'), (1, 'OK')], default=1)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ScheduleDate')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ScheduleUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
