# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_scheduleregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleuser',
            name='comment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
