# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_scheduleuser_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleregister',
            name='result',
        ),
        migrations.RemoveField(
            model_name='scheduleregister',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='scheduleuser',
            name='schedule',
        ),
    ]
