# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20160413_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleuser',
            name='schedule',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule'),
            preserve_default=False,
        ),
    ]
