# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_scheduleregister_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleregister',
            name='schedule',
        ),
    ]
